@host = http://localhost:8000
@token = Bearer e975b15aa477ee440417ea069e8ef728a22933f0
@username = tester
@id = 5
@token = adfasfda


###### example api
GET {{host}}/api/alpha HTTP/1.1
Authorization: Bearer {{token}}

### ------------------   CRUD customers   -------------------
GET {{host}}/api/customers?page=2 HTTP/1.1
Content-Type: application/json

### test 1
POST {{host}}/api/customers HTTP/1.1
content-type: application/json

{
    "name": "dinhhaiphong",
    "email": "tienhoang123@gmail.com",
    "password": "123456ngotieP",
    "phone": "012345678"
}

###
GET {{host}}/api/customers/{{id}} HTTP/1.1
Content-Type: application/json

### 
PUT {{host}}/api/hotels/{{id}} HTTP/1.1
content-type: application/json

{
    "address": "89 lang ha",
    "phone": "0942863806",
    "name": "khach san hoang gia"
}

### 
DELETE  {{host}}/api/hotels/{{id}}  HTTP/1.1
content-type: application/json

### ------------------   CRUD hotels   -------------------
GET {{host}}/api/hotels HTTP/1.1
Content-Type: application/json

### 
POST {{host}}/api/hotels HTTP/1.1
content-type: application/json

{
    "name": "vinhome6",
    "address": "49 nguyen chi thanh",
    "phone": "0912924444"
}

###
GET {{host}}/api/hotels/6 HTTP/1.1
Content-Type: application/json

### 
PUT {{host}}/api/hotels/{{id}} HTTP/1.1
content-type: application/json

{
    "address": "89 lang ha",
    "phone": "0942863806",
    "name": "khach san hoang gia"
}

### 
DELETE  {{host}}/api/hotels/6  HTTP/1.1
content-type: application/json



