@host = http://localhost:8000
@token = Bearer e975b15aa477ee440417ea069e8ef728a22933f0
@username = tester
@id = 5
@token = adfasfda


###### example api

### ------------------   CRUD customers   -------------------
GET {{host}}/api/customers HTTP/1.1
Content-Type: application/json

### test 1
POST {{host}}/api/customers HTTP/1.1
content-type: application/json

{
    "name": "nguyen thị huyen",
    "email": "nguyenhuyen95@gmail.com",
    "password": "Kimoanh1993",
    "phone": "0989897999"
}

###
GET {{host}}/api/customers/2 HTTP/1.1
Content-Type: application/json

### 
PUT {{host}}/api/customers/20 HTTP/1.1
content-type: application/json

{
     "email": "nguyenthanh98@gmail.com",
    "name": "khach san hoang gia",
    "phone": "0942863806",
}

### 
DELETE  {{host}}/api/customers/{{id}}  HTTP/1.1
content-type: application/json


### ------------------   CRUD hotels   -------------------
GET {{host}}/api/hotels?name=vinhome4&page=1 HTTP/1.1
Content-Type: application/json

### 
POST {{host}}/api/hotels HTTP/1.1
content-type: application/json

{
    "name": "vinhome10",
    "address": "120 nguyen chi thanh",
    "phone": "0913924444"
}

###
GET {{host}}/api/hotels/10 HTTP/1.1
Content-Type: application/json

### 
PUT {{host}}/api/hotels/3 HTTP/1.1
content-type: application/json

{
    "address": "89 láng hạ",
    "phone": "0942863806",
    "name": "VP bank"
}

### 
DELETE  {{host}}/api/hotels/8  HTTP/1.1
content-type: application/json


### ------------------   CRUD ROOMS  -------------------
GET {{host}}/api/hotels/1/rooms HTTP/1.1
Content-Type: application/json

###
GET {{host}}/api/hotels/1/rooms/2 HTTP/1.1
Content-Type: application/json

### Create rooms
POST {{host}}/api/hotels/1/rooms HTTP/1.1
content-type: application/json

{   
    "hotel_id":1,
    "name": "vip8888888",
    "description": "full option",
    "floor":4,
    "number": 401,
    "bed": 2,
}

### 
PUT {{host}}/api/hotels/1/rooms/6 HTTP/1.1
content-type: application/json

{
    "name": "khach san hoang gia",
    "description": "full option",
    "floor": 2,
    "description": "full option",
    "number":202,
    "bed": 3,
}

### 
DELETE  {{host}}/api/hotels/1/rooms/{{{id}}} HTTP/1.1
content-type: application/json



### ------------------   CRUD BOOKINGS -------------------

// get all booking 
GET {{host}}/api/hotels/1/rooms/2/bookings HTTP/1.1
Content-Type: application/json

### // Get onebooking 
GET {{host}}/api/hotels/1/rooms/2/bookings/2 HTTP/1.1
Content-Type: application/json

### Create booking
POST {{host}}/api/hotels/2/rooms/2/bookings HTTP/1.1
content-type: application/json

{   
    "room_id":2,
    "customer_id":23,
    "title": "Chi Nga dat phong ",
    "content": "hop team IOS",
    "started_at":"2021-05-04 08:30:00",
    "ended_at": "2021-05-04 09:30:00"
}
//done

### UPDATE booking
PUT {{host}}/api/hotels/1/rooms/2/bookings/4 HTTP/1.1
content-type: application/json

{
    "room_id": 2,
    "customer_id": 20,
    "title": "chi Nga đặt phòng",
    "content": "Tat niên chi nhanh Lang Ha",
    "started_at":"2021-05-15 13:00:00",
    "ended_at": "2021-05-15 15:00:00"
}
 // deletebooking

### 
DELETE  {{host}}/api/hotels/1/rooms/2/bookings/5 HTTP/1.1
content-type: application/json

### 
liệt kê 2 booking 
Booking 1: 
start: "2021-05-15 12:00:00",
end:"2021-05-15 13:00:00"
Booking 2:
start: "2021-05-15 13:00:00",
end:"2021-05-15 15:00:00"
Booking 3:
cung ngay nhu tren nhung tu luc 10h den 12h 
start:"2021-05-15 10:00:00",
end: "2021-05-15 12:00:00"
todo  check booking 3 so voi booking 1 vs 2
startbooking 3 phai lon hon end  cua booking 1 thi moi dat dc
start cua booking 2 phai lon  hon end cua booking 3
end booking 1<start booking 3 >
so sanh start va end cua booking moi voi tat ca booking cu 
neu nos k co loi moi tiep tuc create booking con co loi thi dung vong lap ko tiep tuc check nua va tra ra loi 
### Create booking
POST {{host}}/api/hotels/2/rooms/2/bookings HTTP/1.1
content-type: application/json

{   
    "room_id":2,
    "customer_id":23,
    "title": "Test đặt phòng",
    "content": "sinh nhat công ty",
    "started_at":"2021-05-04 06:30:00",
    "ended_at": "2021-05-04 08:00:00"
}
